### ISSUE TITLE
Please add the discord?

### ISSUE THREAD

**Issue by MargaretCatter** [LearnTeachCode/code-coffee-compendium#64]
https://discord.gg/PKrAxvy

**Comment by LearningNerd** [comment]
Hi @MargaretCatter! I posted a message on the Discord to discuss this with you all, but posting here too to keep this conversation transparent to all our organizers.

My only concern is that having two async chat communities could cause some confusion / splintering for the Learn Teach Code community as a whole. But I'd like your thoughts on this! Here's how I'm currently looking at it:

**Pros of adding an official LTC Discord:**
  - Different vibe compared to Slack, some people associate Discord more with tinkering / tech / friends, whereas many people think of Slack as associated with work (@capsulecorplab made this point)
  - Voice chat feature is definitely nice for those who prefer it for study groups or casual convos with friends

**Cons:**
  - More work for moderators / needing more people to moderate on each platform
  - May be confusing for new LTC members in deciding which platform to use if they want to keep in touch with us
  - Will have less people using each platform, which may mean less active discussion on both platforms

**Some background on our Slack:**

  - We created our Slack channel 5 years ago in 2015 to have a central place to talk and coordinate virtually, and overall I think it's worked very well for that purpose
  - Our Slack has 4,000 members total and about 130 weekly active members posting, both in public channels but also 20% of messages viewed are in private messages (interesting, I think that's a good sign showing people use it to coordinate and collaborate directly)
  - In the past, our most active meetup organizers and myself have discussed moving to Discord since it does have some nice features, but we ultimately decided not to because just about everyone we asked was fine with Slack, and getting everybody to make a new account and move to a new app would be inconvenient and split up the group.

Anyhow, I'd love to hear from more people to bring up points that I hadn't considered above. I think this is a good time to discuss how to make the most of all these online platforms available to us since we're meeting 100% virtually for a while.

(_cc: @capsulecorplab @sugarsyntax @jbazalar @cynful @TristanDamron @KChorseraddish @armaneous and of course anyone from our community is welcome to post here!_)

**Comment by armaneous** [comment]
Chiming in here so that the conversation is public.

I anticipate that a migration to another platform will incur ~90% of user loss; only ~400 will make the jump. Slack does have irregular periods of activity and I'd estimate there are only about 200 or so that are monthly active users in public channels. I don't know if those are the same as ones active in private channels and direct messages. Also, unless the Slack is shut down altogether, it's likely that a portion of users will continue to use it despite an announced migration. Perhaps that's acceptable?

Personally, I'd really rather not be tied to yet another company. Discord is repositioning itself to more directly compete with Slack, probably because its valuation has raised some eyebrows, but I worry about its business model changing. We could wind up in the same situation we're in with Slack's limitations on free teams. Mattermost seems interesting because of that, but we incur operational overhead and a small monthly fee. Not too worried about the latter, but I don't think I can sustainably commit to the former long-term.

If we're not talking about a migration, there is definitely a fracturing of the community that'll happen by maintaining more than one platform. And that's aside from the operational overhead mentioned already with moderation and guiding new members towards which community is right for them.

I'm not saying the Slack is the best, either. I just think we should be very careful with the decision we make and have a thorough, inclusive plan.

**Comment by capsulecorplab** [comment]
I personally don't mind having both Slack and Discord. To use a space exploration metaphor, we're not migrating, we're merely colonizing another of planet (platform). Slack can remain as the _front facing_ community forum, which perhaps caters itself to a more professional/networking and newcomer friendly atmosphere, where as the Discord can serve more special interest topics, e.g., infosec, game dev, technical writing, etc. It's also worth mentioning Discord (at the moment) has unlimited message storage, so you don't lose messages unlike Slack's free tier.
